version: '3.8'

networks:
  cenobridge:
    external:
      name: host
  caddy:
    external:
      name: host
volumes:
  bridge_storage:
  caddy_data:
    external: true
  caddy_config:
    external: true
  synapse_data:
    external: true
  mailadm_db:
services:
  # ceno-client "bridge" service is below
  bridge:
    image: equalitie/ceno-client:latest
    networks:
      - cenobridge
    volumes:
      - bridge_storage:/var/opt/ouinet
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dwebstackrole == bridge
        max_replicas_per_node: 1
      resources:
        limits:
          memory: 512M
  # caddy acts as a reverse proxy for synapse (matrix)
  caddy:
    image: caddy:latest
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - type: bind
        source: /var/www/dcomms
        target: /www
    networks:
      - caddy
    environment:
          DWEB_DOMAIN: "${DWEB_DOMAIN}"
    configs:
      - source: caddy-caddyfile-config
        target: /etc/caddy/Caddyfile
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dwebstackdomain == ${DWEB_DOMAIN}
        max_replicas_per_node: 1
      resources:
        limits:
          memory: 512M
  # synapse is a matrix homeserver running as a service
  synapse:
    image: matrixdotorg/synapse:v1.53.0
    entrypoint:
    - sh
    - -c
    - chown -R 991:991 /data ; /start.py
    volumes:
      - synapse_data:/data
    networks:
      - caddy
    environment:
      SYNAPSE_CONFIG_DIR: "/data"
      SYNAPSE_DATA_DIR: "/data"
      TZ: "UA"
    depends_on:
      - caddy
    configs:
      - source: synapse-homeserver-config
        target: /data/homeserver.yaml
        uid: '991'
        gid: '991'
        mode: 0644
      - source: synapse-signingkey-config
        target: /data/matrix.${DWEB_DOMAIN}.signing.key
        uid: '991'
        gid: '991'
        mode: 0644
      - source: synapse-logconfig-config
        target: /data/matrix.${DWEB_DOMAIN}.log.config
        uid: '991'
        gid: '991'
        mode: 0644
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dwebstackdomain == ${DWEB_DOMAIN}
        max_replicas_per_node: 1
      resources:
        limits:
          memory: 512M
  # element is a matrix web GUI running as a service
  element:
    image: vectorim/element-web:v1.10.4
    networks:
      - caddy
    depends_on:
      - caddy
      - synapse
    configs:
      - source: element-json-config
        target: /app/config.json
      - source: element-nginx-config
        target: /etc/nginx/conf.d/default.conf
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dwebstackdomain == ${DWEB_DOMAIN}
        max_replicas_per_node: 1
      resources:
        limits:
          memory: 512M
  # postfix is running as a part of the delta chat service
  postfix:
    image: keith/deltachat-mailadm-postfix:v0.0.3
    entrypoint:
    - sh
    - -c
    - "postconf -M submission/inet=\"submission inet n - n - - smtpd\" && postconf -P submission/inet/syslog_name=postfix/submission && postconf -P submission/inet/smtpd_tls_security_level=encrypt && postconf -P submission/inet/smtpd_sasl_type=dovecot && postconf -P submission/inet/smtpd_sasl_path=inet:localhost:12345 && postconf -P submission/inet/smtpd_sasl_auth_enable=yes && postconf \"myhostname=${DWEB_DOMAIN}\" && postconf \"mydestination=\" && postconf \"virtual_mailbox_domains=${DWEB_DOMAIN}\" && postconf \"virtual_transport=lmtp:localhost:24\" && postconf \"virtual_mailbox_base=/home/vmail\" && postconf \"virtual_mailbox_maps=texthash:/var/lib/mailadm/virtual_mailboxes\" && postconf \"maillog_file=/dev/stdout\" && postconf \"smtpd_tls_cert_file=/certs/fullchain.pem\" && postconf \"smtpd_tls_key_file=/certs/privkey.pem\" && postfix start-fg"
    volumes:
      - mailadm_db:/var/lib/mailadm/
      - /var/lib/docker/volumes/caddy_data/_data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/${DWEB_DOMAIN}/${DWEB_DOMAIN}.crt:/certs/fullchain.pem
      - /var/lib/docker/volumes/caddy_data/_data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/${DWEB_DOMAIN}/${DWEB_DOMAIN}.key:/certs/privkey.pem
    environment:
      MAIL_DOMAIN: "${DWEB_DOMAIN}"
    networks:
      - caddy
    depends_on:
      - caddy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dwebstackdomain == ${DWEB_DOMAIN}
        max_replicas_per_node: 1
      resources:
        limits:
          memory: 512M
  # dovecot is running as a part of the delta chat service
  dovecot:
    image: keith/deltachat-mailadm-dovecot:v0.0.1
    volumes:
      - mailadm_db:/var/lib/mailadm/
      - /var/lib/docker/volumes/caddy_data/_data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/${DWEB_DOMAIN}/${DWEB_DOMAIN}.crt:/certs/fullchain.pem
      - /var/lib/docker/volumes/caddy_data/_data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/${DWEB_DOMAIN}/${DWEB_DOMAIN}.key:/certs/privkey.pem
    environment:
      VMAIL_UID: "${VMAIL_UID}"
      VMAIL_GID: "${VMAIL_GID}"
    networks:
      - caddy
    depends_on:
      - caddy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dwebstackdomain == ${DWEB_DOMAIN}
        max_replicas_per_node: 1
      resources:
        limits:
          memory: 512M
  # mailadm is running as a part of the delta chat service
  mailadm:
    image: keith/deltachat-mailadm:v0.0.1
    entrypoint:
    - sh
    - -c
    - mailadm init --web-endpoint="https://${DWEB_DOMAIN}/new_email" --mail-domain=${DWEB_DOMAIN} --vmail-user=vmail ; mailadm add-token ZMqbnG8P --maxuse 100000 --expiry 999d --token ZMqbnG8P ; gunicorn -b :3691 -w 1 mailadm.app:app
    volumes:
      - mailadm_db:/var/lib/mailadm/
    environment:
      MAIL_DOMAIN: "${DWEB_DOMAIN}"
      VMAIL_UID: "${VMAIL_UID}"
      VMAIL_GID: "${VMAIL_GID}"
      WEB_ENDPOINT: "https://${DWEB_DOMAIN}/new_email"
    networks:
      - caddy
    depends_on:
      - caddy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.dwebstackdomain == ${DWEB_DOMAIN}
        max_replicas_per_node: 1
      resources:
        limits:
          memory: 512M
configs:
  caddy-caddyfile-config:
    template_driver: golang
    file: ./conf/caddy/Caddyfile.tmpl
    external: false
  synapse-homeserver-config:
    file: ./conf/synapse/${DWEB_DOMAIN}.homeserver.yaml
    external: false
  synapse-signingkey-config:
    file: ./conf/synapse/${DWEB_DOMAIN}.signing.key
    external: false
  synapse-logconfig-config:
    file: ./conf/synapse/${DWEB_DOMAIN}.log.config
    external: false
  element-json-config:
    template_driver: golang
    file: ./conf/element/$DWEB_DOMAIN.config.json
    external: false
  element-nginx-config:
    template_driver: golang
    file: ./conf/element/nginx.conf
    external: false
